import Head from "next/head";
import ArticleList from "../components/ArticleList";
import { server } from "imr/config";

export default function Home({ articles }) {
  return (
    <>
      <Head>
        <title>WebDev News</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ArticleList articles={articles} />
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(`${server}/api/articles`);
  const articles = await res.json();
  return {
    props: {
      articles,
    },
  };
};
// export const getStaticProps = async () => {
//   const END_POINT = "https://jsonplaceholder.typicode.com/posts?_limit=6";
//   const response = await fetch(END_POINT);
//   const articles = await response.json();
//   return {
//     props: {
//       articles,
//     },
//   };
// };
